"""Phase 10 step 2: measure the narrative signal layer.

Four questions, each with a number attached rather than an assurance.

**SC-03 -- are the quotes verbatim?** Every emitted quote is sliced back out of
the document it claims to come from and compared. This is an invariant, so the
only acceptable result is zero failures, and the script says so loudly if it
is not.

**A-10 -- can the sections be located at scale?** Phase 4 built section
detection and measured it on 12 filings; [A-10](../docs/assumptions.md) has
been carrying "accuracy on a labelled sample still due in Phase 10" ever since.
Here it is measured over the whole corpus, per section, with the failures
broken out by kind.

**QM-04 -- precision and recall.** Precision is measured on a hand-labelled
sample of emitted signals; recall against a deliberately over-broad candidate
sweep, also hand-labelled. Both label files live in `evaluation/` and are
committed, because a hand label is the one artefact in this project that
cannot be regenerated by re-running anything. This script emits the pools to
label and scores whatever labels exist; it never invents them.

**Discriminative validity -- does any of it track the outcome?** The corpus
carries the Phase 8 365-day bankruptcy label, so each signal's rate in filings
that preceded a petition can be compared with its rate in filings that did
not. This is the measurement that decides `Specificity` in the catalog, and it
is the one that does not depend on my own labelling at all.

    uv run python scripts/phase10_evaluate.py
    uv run python scripts/phase10_evaluate.py --emit-label-pools
"""

from __future__ import annotations

import argparse
import json
import logging
import random
from collections import defaultdict
from pathlib import Path
from typing import Any

import pandas as pd

from credit_risk_copilot.extraction.base import DocumentExtractionError
from credit_risk_copilot.extraction.html_extractor import HtmlDocumentExtractor
from credit_risk_copilot.extraction.models import DocumentSource, ExtractedDocument
from credit_risk_copilot.logging_config import configure_logging
from credit_risk_copilot.nlp import CATALOG, analyze_document, verify_quotes
from credit_risk_copilot.nlp.models import Assertion, NarrativeRiskReport, RiskSignalCode
from credit_risk_copilot.nlp.recall_sweep import sweep_candidates

logger = logging.getLogger(__name__)

OUT_DIR = Path("data/processed/phase10")
LABEL_DIR = Path("evaluation")
#: The development sample that diagnosed the catalog's false-positive classes
#: was drawn at seed 20260918 and is kept at
#: `evaluation/phase10_development_labels.csv`. The **reported** precision is
#: measured on a fresh draw at this seed, so the number is not quoted on the
#: sample the patterns were repaired against.
RANDOM_SEED = 20260919

#: How many emitted signals to put in the precision pool. Large enough that a
#: per-signal rate means something, small enough to label by hand honestly.
PRECISION_POOL_SIZE = 200
#: How many broad-sweep candidates to put in the recall pool.
RECALL_POOL_SIZE = 150


def _extract(row: pd.Series) -> ExtractedDocument | None:
    path = Path(str(row["html_path"]).replace("\\", "/"))
    if not path.exists():
        return None
    source = DocumentSource(
        uri=str(path),
        media_type="text/html",
        cik=int(row["cik"]),
        accession=str(row["accession"]),
        form=str(row["form"]),
        filed=str(row["filed"]),
    )
    try:
        return HtmlDocumentExtractor().extract(path.read_bytes(), source)
    except (DocumentExtractionError, ValueError) as error:
        logger.warning("extraction failed for %s: %s", row["accession"], error)
        return None


def _run_corpus(
    corpus: pd.DataFrame,
) -> tuple[list[dict[str, Any]], list[dict[str, Any]], list[str]]:
    """Per-filing results, per-signal rows, and any SC-03 failures."""
    per_filing: list[dict[str, Any]] = []
    per_signal: list[dict[str, Any]] = []
    sc03_failures: list[str] = []

    for position, (_, row) in enumerate(corpus.iterrows(), start=1):
        document = _extract(row)
        if document is None:
            per_filing.append(
                {
                    "accession": row["accession"],
                    "cik": row["cik"],
                    "company": row["company"],
                    "label": row["label"],
                    "extracted": False,
                }
            )
            continue

        report = analyze_document(document, company=str(row["company"]))
        sc03_failures.extend(
            f"{row['accession']}: {failure}" for failure in verify_quotes(report, document)
        )
        # The same document, ungated. This is what a keyword matcher over the
        # same patterns would have reported, and the difference between the two
        # is the measurement of D-035's central claim. Computed from the
        # already-parsed document, so it costs pattern matching rather than a
        # second extraction.
        ungated = analyze_document(document, company=str(row["company"]), emit_hypothetical=True)

        located = {c.section_id: c for c in report.coverage}
        record: dict[str, Any] = {
            "accession": row["accession"],
            "cik": row["cik"],
            "company": row["company"],
            "label": row["label"],
            "cohort": row["cohort"],
            "filed": row["filed"],
            "prediction_date": row["prediction_date"],
            "days_to_event": row.get("days_to_event"),
            "extracted": True,
            "characters": len(document.text),
            "n_asserted": len(report.asserted),
            "n_all": len(report.signals),
            "n_ungated": len(ungated.signals),
            "n_codes_asserted": len(report.codes()),
            "n_codes_ungated": len(ungated.codes(asserted_only=False)),
        }
        for code in RiskSignalCode:
            record[f"ungated_{code.value}"] = any(signal.code is code for signal in ungated.signals)
        for section_id, coverage in located.items():
            record[f"located_{section_id}"] = coverage.located
            record[f"sentences_{section_id}"] = coverage.sentences
        for code in RiskSignalCode:
            record[code.value] = any(signal.code is code for signal in report.asserted)
        per_filing.append(record)
        per_signal.extend(_signal_rows(report, row))
        per_signal.extend(
            row_dict | {"gated_out": True}
            for row_dict in _signal_rows(ungated, row)
            if row_dict["assertion"]
            in (Assertion.HYPOTHETICAL.value, Assertion.CROSS_REFERENCE.value)
        )

        if position % 25 == 0 or position == len(corpus):
            logger.info("analysed %d/%d filings", position, len(corpus))

    return per_filing, per_signal, sc03_failures


def _signal_rows(report: NarrativeRiskReport, row: pd.Series) -> list[dict[str, Any]]:
    return [
        {
            "accession": report.accession,
            "cik": report.cik,
            "company": report.company,
            "label": row["label"],
            "code": signal.code.value,
            "pattern_id": signal.pattern_id,
            "assertion": signal.assertion.value,
            "specificity": signal.specificity.value,
            "section_id": signal.quote.section_id,
            "char_start": signal.quote.char_start,
            "char_end": signal.quote.char_end,
            "trigger": signal.quote.trigger_text,
            "quote": signal.quote.text.replace("\n", " "),
        }
        for signal in report.signals
    ]


def _section_coverage(per_filing: pd.DataFrame) -> dict[str, Any]:
    """A-10, measured: how often each narrative section is located."""
    extracted = per_filing[per_filing["extracted"]]
    out: dict[str, Any] = {
        "note": "A-10: MD&A and Risk Factors can be located in 10-K HTML reliably enough for "
        "NLP. Measured here over the whole corpus rather than the 12-filing golden set.",
        "filings": int(len(extracted)),
    }
    for section_id in ("item_1a", "item_3", "item_7"):
        column = f"located_{section_id}"
        if column not in extracted:
            continue
        located = extracted[column].fillna(False).astype(bool)
        out[section_id] = {
            "located": int(located.sum()),
            "rate": round(float(located.mean()), 4),
            "median_sentences": int(
                extracted.loc[located, f"sentences_{section_id}"].median() if located.any() else 0
            ),
        }
    both = extracted.get("located_item_1a", pd.Series(dtype=bool)).fillna(False).astype(
        bool
    ) & extracted.get("located_item_7", pd.Series(dtype=bool)).fillna(False).astype(bool)
    out["item_1a_and_item_7"] = {
        "located": int(both.sum()),
        "rate": round(float(both.mean()), 4) if len(both) else 0.0,
    }
    return out


def _discrimination(per_filing: pd.DataFrame) -> dict[str, Any]:
    """Each signal's rate in pre-bankruptcy filings versus the rest.

    Deliberately reported as two rates and their ratio rather than as a single
    score. A lift of 8x on a signal that appears in 3% of event filings and a
    lift of 1.2x on one that appears in 60% are different kinds of fact, and
    collapsing them into one number would hide which is which.
    """
    extracted = per_filing[per_filing["extracted"]]
    events = extracted[extracted["label"] == 1]
    comparisons = extracted[extracted["label"] == 0]
    if events.empty or comparisons.empty:
        return {"note": "corpus lacks both classes"}

    rows: list[dict[str, Any]] = []
    for code in RiskSignalCode:
        column = code.value
        if column not in extracted:
            continue
        event_rate = float(events[column].mean())
        comparison_rate = float(comparisons[column].mean())
        rows.append(
            {
                "code": column,
                "event_rate": round(event_rate, 4),
                "comparison_rate": round(comparison_rate, 4),
                "lift": (round(event_rate / comparison_rate, 2) if comparison_rate > 0 else None),
                "event_filings": int(events[column].sum()),
                "comparison_filings": int(comparisons[column].sum()),
            }
        )
    rows.sort(key=lambda r: -r["event_rate"])

    any_high = [c.code.value for c in CATALOG if c.specificity.value == "high"]
    events_any = events[any_high].any(axis=1)
    comparisons_any = comparisons[any_high].any(axis=1)

    return {
        "event_filings": int(len(events)),
        "comparison_filings": int(len(comparisons)),
        "per_signal": rows,
        "any_high_specificity_signal": {
            "event_rate": round(float(events_any.mean()), 4),
            "comparison_rate": round(float(comparisons_any.mean()), 4),
            "lift": (
                round(float(events_any.mean()) / float(comparisons_any.mean()), 2)
                if comparisons_any.mean() > 0
                else None
            ),
        },
    }


def _assertion_gate_effect(per_signal: pd.DataFrame, per_filing: pd.DataFrame) -> dict[str, Any]:
    """What the gate withholds -- the layer's central design claim (D-035).

    The comparison that matters is not "how many matches were dropped" but
    "how many filings would have been flagged anyway". A gate that halves the
    signal count but still flags every filing has achieved nothing.
    """
    if per_signal.empty:
        return {}
    extracted = per_filing[per_filing["extracted"]]
    counts = per_signal["assertion"].value_counts().to_dict()

    ungated_columns = [f"ungated_{code.value}" for code in RiskSignalCode]
    present = [c for c in ungated_columns if c in extracted]
    gated_columns = [code.value for code in RiskSignalCode if code.value in extracted]

    out: dict[str, Any] = {
        "note": "the gate withholds hypothetical and cross-reference matches; 'ungated' is what "
        "the same patterns report without it, i.e. a keyword matcher",
        "matches_by_assertion": {str(k): int(v) for k, v in counts.items()},
        "mean_signals_per_filing": {
            "gated": round(float(extracted["n_asserted"].mean()), 1),
            "ungated": round(float(extracted["n_ungated"].mean()), 1),
        },
        "mean_distinct_codes_per_filing": {
            "gated": round(float(extracted["n_codes_asserted"].mean()), 2),
            "ungated": round(float(extracted["n_codes_ungated"].mean()), 2),
        },
    }
    if present and gated_columns:
        out["filings_flagged_by_any_signal"] = {
            "gated": round(float(extracted[gated_columns].any(axis=1).mean()), 4),
            "ungated": round(float(extracted[present].any(axis=1).mean()), 4),
        }
        # The separation a keyword matcher achieves versus what the gate
        # achieves, on the codes with the strongest measured lift.
        for code in (RiskSignalCode.GOING_CONCERN_DOUBT, RiskSignalCode.COVENANT_BREACH):
            if code.value not in extracted:
                continue
            events = extracted[extracted["label"] == 1]
            comparisons = extracted[extracted["label"] == 0]
            out.setdefault("worked_examples", {})[code.value] = {
                "gated": {
                    "event_rate": round(float(events[code.value].mean()), 4),
                    "comparison_rate": round(float(comparisons[code.value].mean()), 4),
                },
                "ungated": {
                    "event_rate": round(float(events[f"ungated_{code.value}"].mean()), 4),
                    "comparison_rate": round(float(comparisons[f"ungated_{code.value}"].mean()), 4),
                },
            }
    return out


def _emit_label_pools(per_signal: pd.DataFrame, corpus: pd.DataFrame) -> None:
    """Write the two hand-labelling pools, stratified and shuffled.

    Stratified by signal code so a rare code is actually represented; shuffled
    with a fixed seed so the labelling order carries no information about
    cohort, which would bias the labeller (me) toward expecting distress in the
    event rows.
    """
    LABEL_DIR.mkdir(parents=True, exist_ok=True)
    rng = random.Random(RANDOM_SEED)

    asserted = per_signal[per_signal["assertion"] == Assertion.ASSERTED.value]
    by_code: dict[str, list[int]] = defaultdict(list)
    for index, code in asserted["code"].items():
        by_code[str(code)].append(int(index))

    per_code = max(1, PRECISION_POOL_SIZE // max(len(by_code), 1))
    chosen: list[int] = []
    for indices in by_code.values():
        rng.shuffle(indices)
        chosen.extend(indices[:per_code])
    rng.shuffle(chosen)

    pool = asserted.loc[chosen[:PRECISION_POOL_SIZE]].copy()
    pool.insert(0, "verdict", "")
    pool.insert(1, "note", "")
    pool = pool[
        ["verdict", "note", "code", "pattern_id", "accession", "company", "section_id", "quote"]
    ]
    path = LABEL_DIR / "phase10_precision_pool.csv"
    pool.to_csv(path, index=False)
    logger.info("wrote %s (%d rows to label)", path, len(pool))

    candidates = sweep_candidates(
        corpus.to_dict("records"), limit=RECALL_POOL_SIZE, seed=RANDOM_SEED
    )
    recall_path = LABEL_DIR / "phase10_recall_pool.csv"
    pd.DataFrame(candidates).to_csv(recall_path, index=False)
    logger.info("wrote %s (%d rows to label)", recall_path, len(candidates))


def _score_labels(per_signal: pd.DataFrame) -> dict[str, Any]:
    """QM-04, scored against whatever hand labels exist on disk."""
    out: dict[str, Any] = {}

    precision_path = LABEL_DIR / "phase10_precision_labels.csv"
    if precision_path.exists():
        labels = pd.read_csv(precision_path)
        labelled = labels[labels["verdict"].isin(["correct", "incorrect"])]
        if len(labelled):
            correct = int((labelled["verdict"] == "correct").sum())
            out["precision"] = {
                "labelled": int(len(labelled)),
                "correct": correct,
                "precision": round(correct / len(labelled), 4),
                "by_code": {
                    str(code): {
                        "labelled": int(len(group)),
                        "correct": int((group["verdict"] == "correct").sum()),
                        "precision": round(float((group["verdict"] == "correct").mean()), 4),
                    }
                    for code, group in labelled.groupby("code")
                },
                "failure_notes": labelled[labelled["verdict"] == "incorrect"]["note"]
                .dropna()
                .tolist(),
            }
    else:
        out["precision"] = {"note": f"no labels at {precision_path}; run --emit-label-pools"}

    recall_path = LABEL_DIR / "phase10_recall_labels.csv"
    if recall_path.exists():
        labels = pd.read_csv(recall_path)
        true_instances = labels[labels["verdict"] == "true_signal"]
        if len(true_instances):
            caught = int((true_instances["caught_by_catalog"].astype(str) == "True").sum())
            out["recall"] = {
                "note": "recall against a deliberately over-broad candidate sweep, hand-labelled. "
                "The denominator is every true instance the sweep surfaced, so this is recall "
                "relative to that sweep's own reach, not to the filing's full content.",
                "true_instances": int(len(true_instances)),
                "caught": caught,
                "recall": round(caught / len(true_instances), 4),
                "missed": true_instances[true_instances["caught_by_catalog"].astype(str) != "True"][
                    ["code", "quote"]
                ].to_dict("records")[:20],
            }
    else:
        out["recall"] = {"note": f"no labels at {recall_path}; run --emit-label-pools"}

    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--emit-label-pools",
        action="store_true",
        help="write the hand-labelling pools instead of only scoring existing labels",
    )
    args = parser.parse_args()

    configure_logging()
    OUT_DIR.mkdir(parents=True, exist_ok=True)

    corpus_path = OUT_DIR / "narrative_corpus.csv"
    if not corpus_path.exists():
        raise SystemExit(f"{corpus_path} not found -- run scripts/phase10_corpus.py first")
    corpus = pd.read_csv(corpus_path)
    corpus = corpus[corpus["error"].isna()].reset_index(drop=True)
    logger.info("analysing %d filings", len(corpus))

    per_filing_rows, per_signal_rows, sc03_failures = _run_corpus(corpus)
    per_filing = pd.DataFrame(per_filing_rows)
    per_signal = pd.DataFrame(per_signal_rows)
    per_filing.to_csv(OUT_DIR / "nlp_per_filing.csv", index=False)
    per_signal.to_csv(OUT_DIR / "nlp_signals.csv", index=False)

    if args.emit_label_pools:
        _emit_label_pools(per_signal, corpus)

    summary: dict[str, Any] = {
        "generated": "phase10_evaluate",
        "corpus": {
            "filings": int(len(corpus)),
            "extracted": int(per_filing["extracted"].sum()),
            "companies": int(corpus["cik"].nunique()),
        },
        "sc03": {
            "quotes_checked": int(len(per_signal)),
            "failures": len(sc03_failures),
            "examples": sc03_failures[:5],
            "invariant_holds": not sc03_failures,
        },
        "a10_section_coverage": _section_coverage(per_filing),
        "assertion_gate": _assertion_gate_effect(per_signal, per_filing),
        "discrimination": _discrimination(per_filing),
        "qm04": _score_labels(per_signal),
    }
    (OUT_DIR / "nlp_evaluation_summary.json").write_text(json.dumps(summary, indent=2))

    logger.info("SC-03: %d quotes checked, %d failures", len(per_signal), len(sc03_failures))
    if sc03_failures:
        logger.error("SC-03 VIOLATED -- %s", sc03_failures[0])
    coverage = summary["a10_section_coverage"]
    for section_id in ("item_1a", "item_7"):
        if section_id in coverage:
            logger.info(
                "A-10 %s located in %.1f%% of filings",
                section_id,
                100 * coverage[section_id]["rate"],
            )
    for row in summary["discrimination"].get("per_signal", [])[:8]:
        logger.info(
            "  %-30s event %.1f%%  comparison %.1f%%  lift %s",
            row["code"],
            100 * row["event_rate"],
            100 * row["comparison_rate"],
            row["lift"],
        )
    logger.info("wrote %s", OUT_DIR / "nlp_evaluation_summary.json")


if __name__ == "__main__":
    main()
